### ISSUE TITLE
High CPU consumption if not connected to a Server

### ISSUE THREAD

**Issue by Frigerius** [sammyfreg/UnrealNetImgui#2] opened 2021-02-03 22:20 UTC
Hey, I have a small server where I run some Game Servers. Since its nice for dev to be able to connect to them with ImGui I kept the dependency to ImGui etc. Since thise time the CPU consumption is above 100% and I think this comes from the fact, that each frame we try to connect smth. even if it is not present, and since I just have 2 Cores this blocks the full server. Do you think this can be improved? Like waiting non blocking on the connection, if this is possible, or would I need to disable ImNetImGui if I don't use it?

**Comment by rtjonnyr** [comment] 2021-02-03 22:44
I was able to fix this with https://github.com/dreamhaven/UnrealNetImgui/commit/39d26687a25c0fdea27e019977ddc5030d8240a5. I'll PR this up to the main repo.

**Comment by Frigerius** [comment] 2021-02-04 07:58
That also fixed it for me, thx, I think I still will do a quick investigation on this topic to check if the game thread could be impacted by this or not but now my system doesn't kill all my containers anymore :D

**Comment by sammyfreg** [comment] 2021-02-04 08:23
Thanks, I'll look into it, but It'll probably be the same change. 

Now, the main repo for this client code is : https://github.com/sammyfreg/netImgui/tree/dev. Would you like to create a pull request there or I could do a similar change and add you in the submit comments.

**Comment by sammyfreg** [comment] 2021-02-04 08:25
@rtjonnyr, don't hesitate to let me know if you have other good fix, I saw that you made some changes that seems right, in your fork. I don't use Unreal on a day to day basis anymore, so there might be some issues I haven't encountered in my small gym.

**Comment by sammyfreg** [comment] 2021-02-04 12:12
After a quick look, I saw that the issue is because I have not configured the Unreal 4 listening socket to be blocking, like on the other platform implementation, so I can either go with the thread sleep, or change the socket to blocking, freeing the thread for other to use.

**Comment by Frigerius** [comment] 2021-02-04 12:16
Hm I'm fine with either, as long it doesn't eat all the performance xD
btw. I currenlty use a custom version of the UnrealImGui NetImGui branch with some modifications to have it work for Servers as well. Do I need to modify smth specific for the 1.8.0 upgrade? (So I have 1.8.0 running, just would need to know if there is smth specifc I'd need to update for NetImGui, and yes, wrong thread .... but I didn't want to add a new thread for this question .... a yes/no would be enough, afterwards I can create thread or write a mail or smth^^)

**Comment by sammyfreg** [comment] 2021-02-04 12:44
As far as I know, updating to _Dear ImGui 1.80_ should be fairly straight forward, with nothing special needed for _NetImgui_. I believe the _UnrealImGui_ plugin is using something a bit older, so there might be a thing or 2 that's not compatible anymore, but shouldn't be major.

**Comment by Frigerius** [comment] 2021-02-04 13:34
Alright, yeah the update was straight forward and it's working for me^^

**Comment by Frigerius** [comment] 2021-02-04 17:08
Hm for me it crashes now on engine shutdown in ClientInfo::KillSocketComs()

**Comment by rtjonnyr** [comment] 2021-02-04 17:19
I have a (poor and temporary) fix for an intermittent shutdown crash too. Let me make a PR for that too. Two threads (module shutdown and the CommunicationsHost thread) are racing against each other.

**Comment by Frigerius** [comment] 2021-02-04 17:20
Ah, makes sense

**Comment by rtjonnyr** [comment] 2021-02-04 18:10
> I have a (poor and temporary) fix for an intermittent shutdown crash too. Let me make a PR for that too. Two threads (module shutdown and the CommunicationsHost thread) are racing against each other.

The temp fix is up at https://github.com/sammyfreg/UnrealNetImgui/pull/5.

**Comment by Frigerius** [comment] 2021-02-05 09:25
thank you, using a FRWLock instead but yeah, that seems to work :)

**Comment by Frigerius** [comment] 2021-02-05 16:41
hmm it still seems to not be 100% stable, since I still get the crash some times^^

**Comment by rtjonnyr** [comment] 2021-02-05 19:16
The crash I fixed occurred when NetImgui is *not* connected. Perhaps you are getting a crash when it is conected? It's likely that all interactions with the global ClientInfo instance require the use of a lock.

**Comment by sammyfreg** [comment] 2021-02-06 00:43
Does the crash only occurs when not connected? I used some atomic states to prevent race condition for all socket, except the listening one (was supposed to be blocking and not repeatedly accessed). Seems that the added mutex on the listening should have taken care fo the problem. I will do some test on my side, and fix this.

**Comment by Frigerius** [comment] 2021-02-06 08:24
It was not connected

**Comment by Frigerius** [comment] 2021-02-06 10:48
need to note, that I increased the wait for 1ms to 10 ms

**Comment by sammyfreg** [comment] 2021-02-07 08:55
Ok, just pushed a revision that hopefully takes care of your crash (2f4737522b93733f063e8374f3262f8927e60b32).

I wasn't able to get the crash with the editor, and wasn't sure how to quickly setup a server. But I believe the changes should take care of the problem (using and closing the listening socket now always on same thread)

**Comment by Frigerius** [comment] 2021-02-08 07:14
Thx, will give it a try today or tomorrow :)

**Comment by Frigerius** [comment] 2021-02-08 15:46
you didn't already do the update for UnrealImGui, right? since I think I can't just copy your NetImguiLibrary code into the plugin, since some method calls seem to have changed xD

**Comment by sammyfreg** [comment] 2021-02-08 16:07
No, I haven't updated it yet. I was fixing issues with this project first while waiting to hear back from the unreal imgui project. Some things changed in netimgui handling of imgui context, that will require some special attention.

**Comment by Frigerius** [comment] 2021-02-08 17:53
Yeah, saw that, was confused xD
But your fix with the race condition seems to work.
If you don't hear back from the other guy would you mind if you help me update my fork? :D

**Comment by rtjonnyr** [comment] 2021-02-08 17:58
I will test the integration of https://github.com/sammyfreg/UnrealNetImgui/commit/2f4737522b93733f063e8374f3262f8927e60b32 into my fork today. That should allow me to get back to being in line with sammyfreg/master. Thanks!

**Comment by rtjonnyr** [comment] 2021-02-08 22:10
This is working great with https://github.com/sammyfreg/UnrealNetImgui/commit/2f4737522b93733f063e8374f3262f8927e60b32 at my end.

**Comment by sammyfreg** [comment] 2021-02-09 12:16
Fixed with 2f4737522b93733f063e8374f3262f8927e60b32
Thank you both for finding the cause.

**Closed as completed by sammyfreg** 2021-02-09 12:16 UTC
Labels: bug

**Comment by sammyfreg** [comment] 2021-02-09 12:19
> 
> 
> Yeah, saw that, was confused xD
> But your fix with the race condition seems to work.
> If you don't hear back from the other guy would you mind if you help me update my fork? :D

I'll take a look over the next 2 weekends.

**Comment by sammyfreg** [comment] 2021-02-14 09:10
Updated Unreal Imgui : https://github.com/sammyfreg/UnrealImGui/tree/Update_1_3
Now waiting for pull request.

**Comment by Frigerius** [comment] 2021-02-15 16:15
cool, thx :)
